IntranetPOPS1819/Models/NoteDeFrais.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace IntranetPOPS1819.Models
{
	public class NoteDeFrais
	{
		public int Id { get; set; }
		public StatutNote Statut { get; set; } = StatutNote.Brouillon;
		public TypeService typeDuService { get; set; }
		[Display(Name = "Note De Frais Associé")]
		public DateTime Date { get; set; }
		public bool Actif { get; set; } = false;
		public virtual List<LigneDeFrais> LignesDeFrais { get; set; } = new List<LigneDeFrais>();
        //public virtual Collaborateur Collaborateur { get; set; }

        public int NbrRefusé()
        {
            int i = 0;
            foreach (LigneDeFrais l in LignesDeFrais)
            {
                if (l.Statut == StatutLigneDeFrais.Refusée)
                {
                    i++;
                }
            }
            return i;
        }
        public int NbrValidée()
        {
            int i = 0;
            foreach (LigneDeFrais l in LignesDeFrais)
            {
                if (l.Statut == StatutLigneDeFrais.Validée)
                {
                    i++;
                }
            }
            return i;
        }


        public int GetSommeValidee()
        {
            int somme = 0;
            foreach(LigneDeFrais ligne in LignesDeFrais)
            {
                if (ligne.Statut == StatutLigneDeFrais.Validée) somme += ligne.Somme;
            }

            return somme;
        }


        public int NbrValidéeChef()
        {
            int i = 0;
            foreach (LigneDeFrais l in LignesDeFrais)
            {
                if (l.Statut == StatutLigneDeFrais.ValidéeChef)
                {
                    i++;
                }
            }
            return i;
        }
        public int NbrEnAttente()
        {
            int i = 0;
            foreach (LigneDeFrais l in LignesDeFrais)
            {
                if (l.Statut == StatutLigneDeFrais.EnAttente)
                {
                    i++;
                }
            }
            return i;
        }
        public bool EstValidéeParLeChef()
		{
			foreach(LigneDeFrais l in LignesDeFrais)
			{
				if(l.Statut != StatutLigneDeFrais.ValidéeChef)
				{
					return false;
				}
			}
			return true;
		}
		public bool EstValidée()
		{
			foreach (LigneDeFrais l in LignesDeFrais)
			{
				if (l.Statut != StatutLigneDeFrais.Validée)
				{
					return false;
				}
			}
			return true;
		}
	}

    public enum StatutNote
    {
        Brouillon,
        EnAttenteDeValidation,
		ValidéeParLeChef,
		Validée,
    }
}

IntranetPOPS1819/Controllers/NoteDeFraisController.cs
using IntranetPOPS1819.Models;
using IntranetPOPS1819.ViewModel;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace IntranetPOPS1819.Controllers
{
    public class NoteDeFraisController : Controller
    {
		private Dal dal;

		public NoteDeFraisController() : this(new Dal())
		{

		}

		private NoteDeFraisController(Dal dalIoc)
		{
			dal = dalIoc;
		}

		public bool EnvoyerNote(int IdNote)
		{
			if (HttpContext.User.Identity.IsAuthenticated)
			{
				System.Diagnostics.Debug.WriteLine("Passage dans EnvoyerNote" + IdNote);
				Collaborateur c = dal.ObtenirCollaborateur(HttpContext.User.Identity.Name);
				dal.EnvoiNoteDeFrais(c.Service.Id, c.Id, IdNote);
				System.Diagnostics.Debug.WriteLine(c.GetNotesDeFraisAValider().Count);
				return true;
			}
			return false;
		}

		public ActionResult LigneDeFrais_Read([DataSourceRequest]DataSourceRequest request, int idNote)
		{
			System.Diagnostics.Debug.WriteLine("Passage dans LigneDeFrais_Read | idNote = " + idNote);
			if (HttpContext.User.Identity.IsAuthenticated)
			{
				dal.MiseAJourNotesDeFrais(HttpContext.User.Identity.Name);
				Collaborateur c = dal.ObtenirCollaborateur(HttpContext.User.Identity.Name);
				NoteDeFrais note = c.NotesDeFrais.FirstOrDefault(n => n.Id == idNote);
				IQueryable<LigneDeFrais> lignedefrais = note.LignesDeFrais.AsQueryable();
				DataSourceResult result = lignedefrais.ToDataSourceResult(request, ligneDeFrais => new {
					Id = ligneDeFrais.Id,
					Nom = ligneDeFrais.Nom,
					Somme = ligneDeFrais.Somme,
					Statut = ligneDeFrais.Statut,
					ResumeFileUrl = ligneDeFrais.ResumeFileUrl,
					Filename = ligneDeFrais.Filename,
					Date = ligneDeFrais.Date,
					Type = ligneDeFrais.Type,
					IdCollab = ligneDeFrais.IdCollab,
                    IdNote = ligneDeFrais.IdNote,
					Commentaire = ligneDeFrais.Commentaire,
                    Mission = new Mission {
						Id = ligneDeFrais.Mission.Id,
						Nom = ligneDeFrais.Mission.Nom,
						Statut = ligneDeFrais.Mission.Statut,
					},
				});
				System.Diagnostics.Debug.WriteLine("Passage dans LigneDeFrais_Read envoie des données : IsComplete a une valuer de " + (note.Statut != StatutNote.Brouillon));
				return Json(result);
			}
			return null;
			
		}

		[AcceptVerbs(HttpVerbs.Post)]
		public ActionResult LigneDeFrais_Create([DataSourceRequest]DataSourceRequest request, LigneDeFrais ligneDeFrais, int n)
		{
			System.Diagnostics.Debug.WriteLine("Passage dans LigneDeFrais_Create | idNote = " + n);
			if (HttpContext.User.Identity.IsAuthenticated)
			{
				var modelStateErrors = ModelState
					.Where(x => x.Value.Errors.Count > 0)
					.Select(x => new { x.Key, x.Value.Errors })
					.ToArray();
				Collaborateur c = dal.ObtenirCollaborateur(HttpContext.User.Identity.Name);
				if (ModelState.IsValid)
				{
					dal.MiseAJourNotesDeFrais(HttpContext.User.Identity.Name);

                    var entity = new LigneDeFrais
                    {
                        Nom = ligneDeFrais.Nom,
                        Somme = ligneDeFrais.Somme,
                        Statut = ligneDeFrais.Statut,
                        ResumeFileUrl = ligneDeFrais.ResumeFileUrl,
                        Filename = ligneDeFrais.Filename,
                        Date = ligneDeFrais.Date,
                        Type = ligneDeFrais.Type,
                        Mission = ligneDeFrais.Mission,
                        IdCollab = ligneDeFrais.IdCollab,
                        IdNote = ligneDeFrais.IdNote,
						Commentaire = ligneDeFrais.Commentaire,
					};
					System.Diagnostics.Debug.WriteLine("Creationd e la ligne dans la BD, Idnote : " + n);
					dal.AjoutLigneDeFrais(c.Id, n, entity);
					ligneDeFrais.Id = entity.Id;
					ligneDeFrais.IdCollab = entity.IdCollab;
					ligneDeFrais.IdNote = entity.IdNote;
				}
				else
				{
					var errors = ModelState.Select(x => x.Value.Errors)
										   .Where(y => y.Count > 0)
										   .ToList();
					System.Diagnostics.Debug.WriteLine("Errors : ModelState isn't valid : ");
					foreach (var v in errors)
					{
						System.Diagnostics.Debug.WriteLine(v);
					}
				}
				if(Session["RESUMEFILE"] != null)
				{
					foreach (HttpPostedFileBase f in Session["RESUMEFILE"] as List<HttpPostedFileBase>)
					{
						DirectoryInfo di = Directory.CreateDirectory(Server.MapPath("~/Justifications/" + c.Id + "/" + ligneDeFrais.Id));
						//f.SaveAs(Server.MapPath("~/Justifications/" + c.Id + "/" + ligneDeFrais.Id + "/" + f.FileName));
						dal.AssocierNomDocument(ligneDeFrais.Id, f.FileName);
						ligneDeFrais.Filename = f.FileName; 
						System.Diagnostics.Debug.WriteLine("Passage dans SaveResumeFile, Nom du fichier enregistré : " + f.FileName + "length" + f.ContentLength);
					}
				}
				Session.Remove("RESUMEFILE");

				System.Diagnostics.Debug.WriteLine("Passage dans LigneDeFrais_Create envoie des données");
				return Json(new[] { ligneDeFrais }.ToDataSourceResult(request, ModelState));
			}
			return null;
		}

		[AcceptVerbs(HttpVerbs.Post)]
		public ActionResult LigneDeFrais_Update([DataSourceRequest]DataSourceRequest request, LigneDeFrais ligneDeFrais)
		{
			
			System.Diagnostics.Debug.WriteLine("Passage dans LigneDeFrais_update");
			if (ModelState.IsValid)
			{
				var entity = new LigneDeFrais
				{
					Id = ligneDeFrais.Id,
					Nom = ligneDeFrais.Nom,
					Somme = ligneDeFrais.Somme,
					Statut = ligneDeFrais.Statut,
					ResumeFileUrl = ligneDeFrais.ResumeFileUrl,
					Filename = ligneDeFrais.Filename,
					Date = ligneDeFrais.Date,
					Type = ligneDeFrais.Type,
					IdCollab = ligneDeFrais.IdCollab,
                    IdNote = ligneDeFrais.IdNote,
					Commentaire = ligneDeFrais.Commentaire,
				};
				dal.bdd.LigneDeFrais.Attach(entity);
				dal.bdd.Entry(entity).State = EntityState.Modified;
				dal.bdd.SaveChanges();
				dal.ChangerMissionLigneDeFrais(ligneDeFrais.Id, ligneDeFrais.Mission.Id);
				System.Diagnostics.Debug.WriteLine("Check Statut de la ligne de frais :" +  entity.Statut.ToString());
				System.Diagnostics.Debug.WriteLine("Check IdCollab de la ligne de frais :" + entity.IdCollab);
				if (entity.Statut == StatutLigneDeFrais.Refusée)
				{
					System.Diagnostics.Debug.WriteLine("Changement Statut de Refusé à EnAttente après édition");
					dal.ChangerStatutLigneDeFrais(entity.Id, StatutLigneDeFrais.EnAttente);
				}
				Collaborateur c = dal.ObtenirCollaborateur(HttpContext.User.Identity.Name);
				if (Session["RESUMEFILE"] != null)
				{
					foreach (HttpPostedFileBase f in Session["RESUMEFILE"] as List<HttpPostedFileBase>)
					{
						DirectoryInfo di = Directory.CreateDirectory(Server.MapPath("~/Justifications/" + c.Id + "/" + ligneDeFrais.Id));
						//f.SaveAs(Server.MapPath("~/Justifications/" + c.Id + "/" + ligneDeFrais.Id + "/" + f.FileName));
						dal.AssocierNomDocument(ligneDeFrais.Id, f.FileName);
						ligneDeFrais.Filename = f.FileName;
						System.Diagnostics.Debug.WriteLine("Passage dans SaveResumeFile, Nom du fichier enregistré : " + f.FileName + "length" + f.ContentLength);
					}
				}
				Session.Remove("RESUMEFILE");

			}
			else
			{
				var errors = ModelState.Select(x => x.Value.Errors)
									   .Where(y => y.Count > 0)
									   .ToList();
				System.Diagnostics.Debug.WriteLine("Errors : ModelState isn't valid : ");
				foreach(var v in errors)
				{
					System.Diagnostics.Debug.WriteLine(v);
				}
			}
			System.Diagnostics.Debug.WriteLine("Passage dans LigneDeFrais_update envoie des données");
			return Json(new[] { ligneDeFrais }.ToDataSourceResult(request, ModelState));
		}

		[AcceptVerbs(HttpVerbs.Post)]
		public ActionResult LigneDeFrais_Destroy([DataSourceRequest]DataSourceRequest request, LigneDeFrais ligneDeFrais)
		{
			System.Diagnostics.Debug.WriteLine("Passage dans LigneDeFrais_destroy");
			if (ModelState.IsValid)
			{
				var entity = new LigneDeFrais
				{
					Id = ligneDeFrais.Id,
					Nom = ligneDeFrais.Nom,
					Somme = ligneDeFrais.Somme,
					Statut = ligneDeFrais.Statut,
					ResumeFileUrl = ligneDeFrais.ResumeFileUrl,
					Filename = ligneDeFrais.Filename,
					Date = ligneDeFrais.Date,
					Type = ligneDeFrais.Type,
					Mission = ligneDeFrais.Mission,
					IdCollab = ligneDeFrais.IdCollab,
                    IdNote = ligneDeFrais.IdNote,
					Commentaire = ligneDeFrais.Commentaire,
				};

				dal.bdd.LigneDeFrais.Attach(entity);
				dal.bdd.LigneDeFrais.Remove(entity);
				dal.bdd.SaveChanges();
			}
			System.Diagnostics.Debug.WriteLine("Passage dans LigneDeFrais_destroy envoie des données");
			return Json(new[] { ligneDeFrais }.ToDataSourceResult(request, ModelState));
		}

		protected override void Dispose(bool disposing)
		{
			dal.bdd.Dispose();
			base.Dispose(disposing);
		}

		[Authorize]
		public ActionResult Index()
		{
			System.Diagnostics.Debug.WriteLine("Passage dans Index GET NoteDeFraisControlleur");
			OngletNoteDeFraisViewModel vm = new OngletNoteDeFraisViewModel { _Authentifie = HttpContext.User.Identity.IsAuthenticated };
			if (HttpContext.User.Identity.IsAuthenticated)
			{
				dal.MiseAJourNotesDeFrais(HttpContext.User.Identity.Name);
				vm._Collaborateur = dal.ObtenirCollaborateur(HttpContext.User.Identity.Name);
			}
			System.Diagnostics.Debug.WriteLine("Passage dans Index GET NoteDeFraisControlleur evnoie des données");
			return View(vm);
		}

		public ActionResult InformationLigneDeFrais(int IdNote)
		{
			System.Diagnostics.Debug.WriteLine("Passage dans InformationLigneDeFrais Get NoteDeFraisControlleur");
			if (HttpContext.User.Identity.IsAuthenticated)
			{
				Collaborateur c = dal.ObtenirCollaborateur(HttpContext.User.Identity.Name);
				List<SelectListItem> list = new List<SelectListItem>();
				foreach (var value in Enum.GetValues(typeof(StatutLigneDeFrais)))
				{
					list.Add(new SelectListItem()
					{

IntranetPOPS1819/Views/NoteDeFrais/Index.cshtml
@using IntranetPOPS1819.Models
@using HelperExtensionNameSpace
@model IntranetPOPS1819.ViewModel.OngletNoteDeFraisViewModel
@{
    ViewBag.Title = "Note De Frais";

    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Html.Partial("../Shared/Navbar")
<div>
    <div class="container-fluid profil-layout">
        <div class="row">
			<div class="col-md-2 row1">
				<p><h3 class="text-center">Historique</h3></p>
				@{
					int a = Model._Collaborateur.NotesDeFrais.Count - 1;
					int d = DateTime.Now.Year;
				<div class="list-group list-group-mine">
					@while (d >= Model._Collaborateur.NotesDeFrais[0].Date.Year && a >= 0)
					{
					<button class="btn btn-block list-group-item btn-1" href=""  onclick="javascript:toggleVisibility(('Année' + @d)); return false;">@Model._Collaborateur.NotesDeFrais[a].Date.Year</button>
					<div id=@(("Année" + d)) style="display:none;">
						@while (a >= 0 && @Model._Collaborateur.NotesDeFrais[a].Date.Year == d)
						{
							string s = Model._Collaborateur.CircleInformationNoteDeFrais(Model._Collaborateur.NotesDeFrais[a].Date.ToString("MMMM"), Model._Collaborateur.NotesDeFrais[a].NbrEnAttente(), Model._Collaborateur.NotesDeFrais[a].NbrRefusé(), Model._Collaborateur.NotesDeFrais[a].NbrValidéeChef(), Model._Collaborateur.NotesDeFrais[a].NbrValidée());
							@Ajax.RawActionLink(string.Format(s), "InformationLigneDeFrais", "NoteDeFrais", new { IdNote = Model._Collaborateur.NotesDeFrais[a].Id }, new AjaxOptions
							{
								InsertionMode = InsertionMode.Replace,
								UpdateTargetId = "InfoNoteActive",
								HttpMethod = "Post"
							}, new { @class = "btn btn-block btn-3 list-group-item" })
							a--;
						}
					</div>
					d--;
					}
				</div>
						}
						
					</div>
					<div class="col-md-10">
						<div id="InfoNoteActive" class="row2">
							@{
								Html.RenderAction("InformationLigneDeFrais", new { IdNote = Model._Collaborateur.NotesDeFrais[Model._Collaborateur.NotesDeFrais.Count - 1].Id });
							}
						</div>
					</div>
				</div>
    </div>
</div>

IntranetPOPS1819/Views/NoteDeFrais/InformationLigneDeFrais.cshtml
@using IntranetPOPS1819.Controllers
@using IntranetPOPS1819.Models

@(Html.Kendo().Grid<IntranetPOPS1819.Models.LigneDeFrais>()
									  .Name("grid")
									  .HtmlAttributes(new { style = "height: 500px" })
									  .Columns(columns =>
									  {
										  columns.Bound(c => c.Nom);
										  columns.Bound(c => c.Somme);
										  columns.Bound(c => c.Mission).ClientTemplate(
												"# if (Mission != null) { #" +
												"<div>#= Mission.Nom #</div>" +
												"#} else {#" +
												"<div> </div>" +
												"# } #"
											);

										  columns.Bound(c => c.Type);
										  columns.Bound(c => c.Date);
										  columns.Bound(e => e.ResumeFileUrl).EditorTemplateName("ResumeFileUrl").Title("Justification").ClientTemplate("#= (Filename) ? Filename : \"Aucun Justificatif\" #"); ;
										  columns.Bound(c => c.Statut).ClientTemplate(
											"# if (Statut == 1){ #" +
											"<font color=\"DarkOrange\">En Attente</font>" +
										"# }else if(Statut == 2){ #" +
											"<font color=\"ForestGreen\">Validée par le chef</font>" +
										"# }else if(Statut == 3){ #" +
											"<font color=\"ForestGreen\">Validée</font>" +
										"# }else{ #" +
											"<font color=\"FireBrick\">Refusée</font>" + "# } #"
											);
										  columns.Command(command => command.Custom("Détail du refus").Click("showDetailRefus").HtmlAttributes(new { @class = "detailRefus" }).Visible("editVisible")).Width(100);
										  columns.Command(command => command.Edit().Text(" ").HtmlAttributes(new { @class = "editer" })).Width(100);
										  columns.Command(command => command.Destroy().IconClass("fa fa-trash").Text(" ").HtmlAttributes(new { @class = "supprimer" })).Width(100);
									  })
											.ToolBar(toolbar =>
											toolbar.Template(@<text>
                                                <div>
                                                    <button class="k-button k-button-icontext k-grid-add" id="AddLigne" href="#"><span class="k-icon k-add"></span>Ajouter une ligne de frais</button>
                                                    <button class="k-button k-button-icontext" id="EnvoyerNote">Envoyer la note de frais</button>
                                                </div>
                                            </text>)
																)
																		.Editable(editable => editable.Mode(GridEditMode.InLine))
																		.Sortable(sortable =>
																		{
																			sortable.SortMode(GridSortMode.SingleColumn);
																		})
																		.Scrollable(scrollable => scrollable.Height("auto"))
																		.Events(events =>
																		{
																			events.Save("onSave");
																			events.SaveChanges("onSaveChanges");
																			events.Edit("onEdit");
																			events.DataBound("onDataBound");
																			events.DataBinding("onDataBinding");
																		})
																		.DataSource(dataSource => dataSource
																			.Ajax()
																			.Model(model =>
																			{
																				model.Field(c => c.Type).DefaultValue(IntranetPOPS1819.Models.TypeLigneDeFrais.Autre);
																				model.Field(c => c.Date).DefaultValue(DateTime.Today);
																				model.Field(c => c.Somme).DefaultValue(0);
																				model.Field(c => c.Statut).DefaultValue(IntranetPOPS1819.Models.StatutLigneDeFrais.EnAttente).Editable(false);
																				model.Field(c => c.Mission).DefaultValue(ViewData["defaultMission"] as IntranetPOPS1819.Models.Mission);
																				model.Id(p => p.Id);
																			})
																			.Read(read => read.Action("LigneDeFrais_Read", "NoteDeFrais", new { idNote = Model }))
																			.Create(create => create.Action("LigneDeFrais_Create", "NoteDeFrais", new { n = Model }))
																			.Update(update => update.Action("LigneDeFrais_Update", "NoteDeFrais"))
																			.Destroy(destroy => destroy.Action("LigneDeFrais_Destroy", "NoteDeFrais"))
																		)
)

												<div class="modal fade" id="msgModalRefusNote" role="dialog">
													<div class="modal-dialog">
														<div class="modal-content">
															<div class="modal-header">
																<h4 class="modal-title text-center">Détail du refus de la ligne de frais</h4>
															</div>
																<div class="modal-body">
																	<div class="form-row">
																		<div class="col-md-12" style=" margin-top: 10px; margin-left:90px">
																			<textarea class="form-control" rows="10" id="texteMessageRefus" disabled></textarea>
																		</div>
																	</div>
																</div>
																<div class="modal-footer">
																	<div class="col-md-12" style="margin-left:90px">
																		<button type="button" class="btn btn-primary" data-dismiss="modal" style="float:right">Fermer</button>
																	</div>
																</div>
														</div>
													</div>
												</div>

<style>
    .editer {
        background-color: #ffc107;
        color: white;
    }

    .supprimer {
        background-color: #dc3545;
        color: white;
    }

    .Disabled {
        pointer-events: none;
        cursor: not-allowed;
        opacity: 0.65;
        filter: alpha(opacity=65);
        -webkit-box-shadow: none;
        box-shadow: none;
    }
</style>

<script>
	function editVisible(dataItem) {
		// hide the Edit button for the item with ProductID=1
		return dataItem.Statut == 0;
	}
</script>
<script type="text/javascript">
	var test = '@ViewData["IsComplete"]';
	if (test == 'True' || '@ViewData["IsOld"]' == 'True') {
		$('#EnvoyerNote').addClass('Disabled');
		$('#AddLigne').addClass('Disabled');
		$('#AddLigne').addClass('disable-button-intranet');
		$('#EnvoyerNote').addClass('disable-button-intranet');
		
	}
	$('#EnvoyerNote').click(function () {
		
		var grid = $("#grid").data("kendoGrid");
		var items = grid.dataSource.data();
		if (items.length == 0) {
			alert('Il n\y a pas de lignes de frais dans cette note. Action impossible.');
		}
		else {
			$.post( "EnvoyerNote", {IdNote: "@Model"}, function( data ) {
				alert('La note de frais a été envoyée');
				$('#EnvoyerNote').addClass('Disabled');
				$('#AddLigne').addClass('Disabled');
				$('#AddLigne').addClass('disable-button-intranet');
				$('#EnvoyerNote').addClass('disable-button-intranet');
			console.log(data);
		});
		}
	});
</script>
<script>
	function showDetailRefus(e) {
		e.preventDefault();
		
		var dataItem = this.dataItem($(e.currentTarget).closest("tr"));
		var texte = document.getElementById('texteMessageRefus');
		if (dataItem.Commentaire != "") {
			texte.value = dataItem.Commentaire;
		}
		else {
			texte.value = "Il n'y a pas d'explication pour le refus de cette ligne de frais";
		}
		$('#msgModalRefusNote').modal('show');
		
	}
	function onSave(e) {
		console.log(e)
        //Implement the event handler for Save
    }

    function onSaveChanges(e) {
        //Implement the event handler for SaveChanges

    }

    function onEdit(e) {

    }

    function onDataBound(e) {
        var grid = $("#grid").data("kendoGrid");
        var gridData = grid.dataSource.view();

        for (var i = 0; i < gridData.length; i++) {

            var currentUid = gridData[i].uid;

            if (gridData[i].Statut == 2 || gridData[i].Statut == 3) {
				var currenRow = grid.table.find("tr[data-uid='" + currentUid + "']");
				
                var editButton = $(currenRow).find(".k-grid-edit");
				var deleteButton = $(currenRow).find(".k-grid-delete");
				var detailRefus = $(currenRow).find(".detailRefus");

                editButton.hide();
				deleteButton.hide();
				detailRefus.hide();
            }
        }
    }

    function onDataBinding(e) {
        //Implement the event handler for DataBinding
    }
    function error_handler(e) {
        if (e.errors) {
            var message = "Errors:\n";
            $.each(e.errors, function (key, value) {
                if ('errors' in value) {
                    $.each(value.errors, function () {
                        message += this + "\n";
                    });
                }
            });
            alert(message);
        }
    }
    function onSelectResumeFile(e) {
        $.each(e.files, function (index, value) {
            var allowedExtensions = ".doc|.docx|.pdf|.png|.jpg";
            if (allowedExtensions.indexOf(value.extension.toLowerCase()) < 0) {
                alert("Ce type de fichier n'est pas supporté.");
                e.preventDefault();
            }
        });
    }
    function onUploadSuccessResumeFile(e) {
        switch (e.response.Type.toString().toLowerCase()) {
            case "upload":
                alert('Le fichier a été uploadé avec succès.');
                break;
            case "remove":
                alert('Le fichier a bien été supprimé.');
                break;
        }
    }
</script>