IntranetPOPS1819/Controllers/ComptaController.cs
using IntranetPOPS1819.Models;
using IntranetPOPS1819.ViewModel;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IntranetPOPS1819.Controllers
{
    public class ComptaController : Controller
    {
		private Dal dal;

		// GET: Compta
		public ActionResult Index()
        {
			ComptaViewModel vm = new ComptaViewModel
			{
				c = dal.ObtenirCollaborateur(HttpContext.User.Identity.Name),
				Services = dal.ObtenirTousLesServices().ToList()
			};
				
			return View(vm);
        }
		

		public ComptaController() : this(new Dal())
		{

		}

		private ComptaController(Dal dalIoc)
		{
			dal = dalIoc;
		}

		public ActionResult ValiderLigne(int Id)
		{
			Collaborateur c = dal.ObtenirCollaborateur(HttpContext.User.Identity.Name);
			System.Diagnostics.Debug.WriteLine("Valider la ligne" + Id);
			dal.ChangerStatutLigneDeFrais(Id, StatutLigneDeFrais.Validée);
			LigneDeFrais ligne = dal.bdd.LigneDeFrais.FirstOrDefault(l => l.Id == Id);
			Collaborateur col = dal.bdd.Collaborateurs.FirstOrDefault(co => co.Id == ligne.IdCollab);
			dal.AjoutNotif(ligne.IdCollab, new Message(TypeMessage.NotifLigneRetour, c, ligne, false));
			foreach (NoteDeFrais n in col.NotesDeFrais)
			{
				if (n.LignesDeFrais.Contains(ligne))
				{
					if (n.LignesDeFrais.Contains(ligne))
					{
						if (n.EstValidée())
						{
							dal.EnvoiNoteDeFrais(col.Service.Id, col.Id, n.Id);
							dal.EnleverNoteDeFraisDuService(n.Id, dal.ObtenirServiceDeType(TypeService.Comptabilité).Id);
							return Json(null, JsonRequestBehavior.AllowGet);
						}
						else
						{
							return null;
						}
					}
				}
			}
			//dal.ValiderConge(c.Id, new Message { Titre = "Validation de Note", Date = DateTime.Now, Contenu = "Une Ligne de frais a été validée par le chef de service"})
			return Json(null, JsonRequestBehavior.AllowGet);
		}

		public ActionResult RefuserLigne(int Id, string message = "")
		{
			Collaborateur c = dal.ObtenirCollaborateur(HttpContext.User.Identity.Name);
			System.Diagnostics.Debug.WriteLine("Refuser La ligne" + Id);
			dal.ChangerStatutLigneDeFrais(Id, StatutLigneDeFrais.Refusée);
			dal.MessageDeRefusLigneDefrais(Id, message);
			LigneDeFrais l = dal.bdd.LigneDeFrais.FirstOrDefault(co => co.Id == Id);
			dal.AjoutNotif(l.IdCollab, new Message(TypeMessage.NotifLigneRetour, c, l, true));
			return Json(null, JsonRequestBehavior.AllowGet);
		}
		public ActionResult LigneDeFrais_Read([DataSourceRequest]DataSourceRequest request, int IdCollab)
		{
			List<LigneDeFrais> l = new List<LigneDeFrais>();
			foreach (NoteDeFrais n in dal.ObtenirCollaborateur(HttpContext.User.Identity.Name).Service.NotesDeFrais)
			{
				if(n.LignesDeFrais[0].IdCollab == IdCollab)
				{
					l.AddRange(n.LignesDeFrais.Where(s => (s.Statut != StatutLigneDeFrais.Validée)));
				}
			}
			IQueryable<LigneDeFrais> lignedefrais = l.AsQueryable();
			
			DataSourceResult result = lignedefrais.ToDataSourceResult(request, ligneDeFrais => new {
				Id = ligneDeFrais.Id,
				Nom = ligneDeFrais.Nom,
				Somme = ligneDeFrais.Somme,
				Type = ligneDeFrais.Type,
				Statut = ligneDeFrais.Statut,
				Date = ligneDeFrais.Date,
				ResumeFileUrl = ligneDeFrais.ResumeFileUrl,
				Filename = ligneDeFrais.Filename,
				Mission = ligneDeFrais.Mission,
				IdCollab = ligneDeFrais.IdCollab,
                IdNote = ligneDeFrais.IdNote,
				Commentaire = ligneDeFrais.Commentaire,
				Note = new NoteDeFrais
				{
					Date = ligneDeFrais.Note.Date
				}
			});

			return Json(result);
		}

		protected override void Dispose(bool disposing)
		{
			dal.bdd.Dispose();
			base.Dispose(disposing);
		}

		public ActionResult InformationLigneDeFrais(int IdCollab)
		{
			return PartialView(IdCollab);
		}
	}
}

IntranetPOPS1819/Views/Compta/Index.cshtml
@using HelperExtensionNameSpace
@using IntranetPOPS1819.Models
@using IntranetPOPS1819.ViewModel
@model ComptaViewModel
@{
	ViewBag.Title = "Service Comptabilité";

	Layout = "~/Views/Shared/_Layout.cshtml";
}

<head>
	@Styles.Render("~/Content/css")
</head>

@Html.Partial("../Shared/Navbar")
@{
	int firstCollab = -1;
	<div>
		<div class="container-fluid">
			<div class="row">
				<div class="col-lg-2 table-bordered">
					<div class="list-group">
						<br />
						<h2 class="text-center">Services</h2>
						<br />
						@foreach (Service s in Model.Services)
						{
							<button class="btn btn-block btn-1 list-group-item" href="" onclick="javascript:toggleVisibility(('service' + @s.Id)); return false;">@s.Nom</button>
							<div id="@("service" + s.Id)" style="display:none;">
								@foreach (Collaborateur c in s.Collaborateurs)
								{
									if (c.Id != Model.c.Id)
									{
										if ((c.Service.Type == TypeService.Direction && c.Chef && Model.c.Chef) || (c.Service.Type == TypeService.Direction && !c.Chef) || c.Service.Type != TypeService.Direction)
										{
											if (firstCollab == -1) { firstCollab = c.Id; }
											@Ajax.RawActionLink(string.Format(c.Prenom + " " +c.Nom), "InformationLigneDeFrais", "Compta", new { IdCollab = c.Id }, new AjaxOptions
										   {
											   InsertionMode = InsertionMode.Replace,
											   UpdateTargetId = "InfoNoteActive",
											   HttpMethod = "Post"
										   }, new { @class = "btn btn-block btn-3 list-group-item" })
										}
									}

								}
							</div>
						}
					</div>
				</div>
				<div class="col-lg-10 table-bordered">
					<div id="InfoNoteActive">
						@{
							if (firstCollab != -1)
							{
								Html.RenderAction("InformationLigneDeFrais", new { IdCollab = firstCollab });
							}
						}
					</div>
				</div>
			</div>
		</div>
	</div>
}

IntranetPOPS1819/Views/Compta/InformationLigneDeFrais.cshtml
@model int
@(Html.Kendo().Grid<IntranetPOPS1819.Models.LigneDeFrais>()
							  .Name("LigneDeFrais")
							  .HtmlAttributes(new { style = "height: 500px" })
							  .Columns(columns =>
							  {
								  columns.Bound(c => c.Nom);
								  columns.Bound(c => c.Somme);
								  
								  columns.Bound(c => c.Date);
								  columns.Bound(c => c.Filename).ClientTemplate("#= (Filename) ? Filename : \"Aucun Justificatif\" #"); ;
								  columns.Bound(c => c.Note.Date).ClientTemplate("#= Note.Date ? kendo.toString(kendo.parseDate(Note.Date), 'y') : '' #");
								  columns.Bound(c => c.Mission).ClientTemplate(
									"#= Mission.Nom #"
								);
								  columns.Bound(c => c.Type);
								  columns.Bound(c => c.Statut).ClientTemplate(
									"# if (Statut == 1){ #" +
										"<font color=\"DarkOrange\">En Attente</font>" +
									"# }else if(Statut == 2){ #" +
										"<font color=\"ForestGreen\">Validée par le chef</font>" +
									"# }else if(Statut == 3){ #" +
										"<font color=\"ForestGreen\">Validée</font>" +
									"# }else{ #" +
										"<font color=\"FireBrick\">Refusée</font>" + "# } #"
									);
								  columns.Command(command => { command.Custom(" Valider").IconClass("fas fa-check").HtmlAttributes(new { @class = "btn btn-success" }).Click("Valider"); command.Custom(" Refuser").IconClass("fas fa-times").HtmlAttributes(new { @class = "btn btn-danger" }).Click("Refuser"); }).Width(220);
							  })
										.Sortable(sortable =>
										{
											sortable.SortMode(GridSortMode.SingleColumn);
										})
										.Scrollable(scrollable => scrollable.Height("auto"))
										.DataSource(dataSource => dataSource
											.Ajax()
											.Model(model => model.Id(p => p.Id))
											.Read(read => read.Action("LigneDeFrais_Read", "Compta", new { IdCollab = Model }))
										)
)

<div class="modal fade" id="msgModalRefusNote" role="dialog">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title text-center">Justifier le refus</h4>
			</div>
			<form id="messageRefus" method="POST">
				<div class="modal-body">
					<div class="form-row">
						<div class="col-md-12" style=" margin-top: 10px; margin-left:90px">
							<textarea class="form-control" rows="10" id="texteMessageRefus"></textarea>
						</div>
					</div>
				</div>
				<div class="modal-footer">
					<div class="col-md-12" style="margin-left:90px">
						<button type="submit" id="submitForm" class="btn btn-primary">Refuser</button>
						<button type="button" class="btn btn-primary" data-dismiss="modal" style="float:right">Fermer</button>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>

<script type="text/javascript">
	var dataOFSelectedLine;
	function Valider(e) {
		var dataItem = this.dataItem($(e.currentTarget).closest("tr"));
		console.log(dataItem);
		var grid = $("#LigneDeFrais").data("kendoGrid");
		var items = grid.dataSource.data();
		for (var i = 0; i < items.length; i++) {
			if (dataItem.Id == items[i].Id) {
				items[i].set("Statut", 3);
			}
		}
		$.ajax({
			url: 'ValiderLigne',
			data: { id: dataItem.Id }
		})
	}

	function Refuser(e) {
		dataOFSelectedLine = this.dataItem($(e.currentTarget).closest("tr"));
		$('#msgModalRefusNote').modal('show');
	}

	$('#messageRefus').on('submit', function (e) {
		e.preventDefault();
		var texte = document.getElementById('texteMessageRefus');
		if (texte.value != "") {
			console.log(dataOFSelectedLine);
			var grid = $("#LigneDeFrais").data("kendoGrid");
			var items = grid.dataSource.data();
			for (var i = 0; i < items.length; i++) {
				if (dataOFSelectedLine.Id == items[i].Id) {
					items[i].set("Statut", 0);
				}
			}
			$.ajax({
				url: 'RefuserLigne',
				data: { id: dataOFSelectedLine.Id, message: texte.value }
			})
			texte.value = "";
		}
		else {
			console.log(dataOFSelectedLine);
			var grid = $("#LigneDeFrais").data("kendoGrid");
			var items = grid.dataSource.data();
			for (var i = 0; i < items.length; i++) {
				if (dataOFSelectedLine.Id == items[i].Id) {
					items[i].set("Statut", 0);
				}
			}
			$.ajax({
				url: 'RefuserLigne',
				data: { id: dataOFSelectedLine.Id }
			})
		}
		$('#msgModalRefusNote').modal('hide');
	});

</script>
<script>

	function onSave(e) {
		//Implement the event handler for Save
	}

	function onSaveChanges(e) {
		//Implement the event handler for SaveChanges
	}

	function onDataBinding(e) {
		//Implement the event handler for DataBinding
	}

</script>